[package]
name = "fetch_day"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.5.4"
reqwest = { version = "0.11.7", features = ["blocking"] }
clap = { version = "3.0.0-beta.5", features = ["derive"] }
chrono = "0.4.19"
